name: Build

on: workflow_dispatch

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      # - name: Init
      #   run: |
      #     echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      # - uses: satackey/action-docker-layer-caching@v0.0.11
        # continue-on-error: true
      - name: Pull and decompile
        run: |
          docker pull registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend
          docker tag registry.cn-hangzhou.aliyuncs.com/onlinejudge/oj_backend backend
          mkdir decompiled
          cd decompiled
          docker save backend --output decompiled.tar
          tar xvf decompiled.tar
          ls -a
          cd ..
      - name: Build
        run: |
          cd OnlineJudgeFE
          npm install
          export NODE_ENV=production
          export TARGET=http://oj-backend:8000
          npm run build:dll
          cd dist
          ls -a

      # - name: Publish
      #   run: |
      #     docker tag runner ghcr.io/livetl/runner:latest
      #     docker push ghcr.io/livetl/runner:latest