name: Build

on: workflow_dispatch

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      # - name: Init
      #   run: |
      #     echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ secrets.CR_USERNAME }} --password-stdin
      # - uses: satackey/action-docker-layer-caching@v0.0.11
        # continue-on-error: true
      - name: Pull and decompile
        run: |
          git clone -b 2.0 https://github.com/QingdaoU/OnlineJudgeDeploy.git
          cd OnlineJudgeDeploy
          docker-compose up -d
      - name: Build
        run: |
          cd OnlineJudgeFE
          npm install
          export NODE_ENV=development
          export TARGET=http://oj-backend:8000
          npm run build:dll
          node_modules/webpack/bin/webpack.js webpack --config=build/webpack.prod.conf.js
          docker ps
          docker cp dist oj-backend:/app/dist

      # - name: Publish
      #   run: |
      #     docker tag runner ghcr.io/livetl/runner:latest
      #     docker push ghcr.io/livetl/runner:latest